print legend for the output
Summary:
F for files, . for procedures, and a few more for developer mode.

Also add the crash message to the crash symbol, because if infer crashes we
want as much information as possible.

```
$ infer -- javac Hello.java
Starting analysis (Infer version v0.8.1-8e8c6fa)

legend:
  "F" analyzing a file
  "." analyzing a procedure

F..

Analyzed 1 file

Found 1 issue

Hello.java:13: error: NULL_DEREFERENCE
  object s last assigned on line 12 could be null and is dereferenced at line 13
  11.     int test() {
  12.       String s = null;
  13. >     return s.length();
  14.     }
  15.   }
  16.

Summary of the reports

  NULL_DEREFERENCE: 1
$ infer -g -- javac Hello.java
...
Starting analysis (Infer version v0.8.1-8e8c6fa)

legend:
  "F" analyzing a file
  "." analyzing a procedure
  "C" analyzer crashed
  "T" timeout: procedure analysis took too much time
  "S" timeout: procedure analysis took too many symbolic execution steps
  "R" timeout: procedure analysis took too many recursive iterations

...
```

Reviewed By: sblackshear

Differential Revision: D3288081

fbshipit-source-id: becea34