[DB] return resolved path when path cannot be made relative
Summary:
This makes it more obvious why infer would force a path to be absolute since we
base that decision on the resolved path. For instance:

```
$ mkdir foo
$ cd foo
$ ln -s ../examples goo
$ infer -- clang -c goo/hello.c
[...]
/home/jul/infer/examples/hello.c:14: error: NULL_DEREFERENCE
```

We see that the path is outside of the current directory clearly, whereas
before infer would report on "goo/hello.c".

Reviewed By: akotulski

Differential Revision: D4409579

fbshipit-source-id: 7172005