Fixes/updates to build on linux.
Summary:
a) An update to build-infer.sh to avoid downloading/building 4.02.3
ocaml compiler when it is already present.
b) Add the ifdef to avoid this error on glibc systems:

    clang -c -w libc_basic.c -o libc_basic.o
    libc_basic.c:692:12: error: unknown type name '__WAIT_STATUS'
    pid_t wait(__WAIT_STATUS stat_loc) {
            ^
Closes https://github.com/facebook/infer/pull/429

Reviewed By: akotulski

Differential Revision: D3704604

Pulled By: jvillard

fbshipit-source-id: d557f1b