[toplevel] small changes in the stdout output
Summary:
After:
```
$ infer run -- clang -c examples/hello.c
Capturing in make/cc mode...
Found 1 source file to analyze in /home/jul/infer/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F.

Found 1 issue

examples/hello.c:14: error: NULL_DEREFERENCE
  pointer `s` last assigned on line 13 could be null and is dereferenced at line 14, column 3
  12.   void test() {
  13.     int* s = NULL;
  14. >   *s = 42;
  15.   }

Summary of the reports

  NULL_DEREFERENCE: 1
```

Before, legend and analysis run were separated by 2 lines, one is now before
and the other is in the log files only:
```
Capturing in make/cc mode...
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 1 (out of 1) source files to be analyzed in /home/jul/infer/infer-out
per-procedure parallelism jobs:4
F.

Found 1 issue

examples/hello.c:14: error: NULL_DEREFERENCE
  pointer `s` last assigned on line 13 could be null and is dereferenced at line 14, column 3
  12.   void test() {
  13.     int* s = NULL;
  14. >   *s = 42;
  15.   }

Summary of the reports

  NULL_DEREFERENCE: 1
```

Reviewed By: mbouaziz

Differential Revision: D5069590

fbshipit-source-id: 8843422