[clang] always print clang errors on stderr
Summary:
clang errors would get diverted to log files instead of being printed on the
console. Also log other types of clang errors and warnings more often.

Before:

  $ infer -- clang -c nosuchfile.c
  $ # nothing gets printed, exit code set to 1

After:

  $ infer -- clang -c nosuchfile.c
  clang-4.0: error: no such file or directory: 'nosuchfile.c'

Also print more messages in case of compilation errors:

  $ echo ')' >> a.c
  $ infer -- clang -c a.c
  a.c:1:1: error: expected identifier or '('
  )
  ^
  1 error generated.
  Error: the following clang command did not run successfully:
    '/home/jul/infer/facebook-clang-plugins/clang/install/bin/clang-4.0' "@/home/jul/infer/examples/infer-out/clang/clang_command_2a0a84.txt"

(only the last 2 lines are new)

Reviewed By: akotulski

Differential Revision: D4183039

fbshipit-source-id: b9a9065