fix printing number of analysed procs/files
Summary: public
When analysing projects we would not always display the numbers of procs and
files analysed. This fixes it, and also prints the stats before the reports for
readability. This way we also don't need to print "Analysis done" anymore.

Before:

  $ infer -- gcc -c hello.c
  Starting analysis (Infer version git-436690cf022a16313dda8447121a5934529e6e5c)
  Analysis done

  hello.c:5: error: NULL_DEREFERENCE
    pointer s last assigned on line 4 could be null and is dereferenced at line 5, column 3
    3.   void test() {
    4.     int *s = NULL;
    5. >   *s = 42;
    6.   }

After:

  $ infer -- gcc -c hello.c
  Starting analysis (Infer version git-5b7ff3ac10d58e7ffd17c44574ab330ed07cb188)
  Computing dependencies... 100%
  Analyzing 1 cluster. 100%
  Analyzed 1 procedure in 1 file

  Found 1 issue

  hello.c:5: error: NULL_DEREFERENCE
    pointer s last assigned on line 4 could be null and is dereferenced at line 5, column 3
    3.   void test() {
    4.     int *s = NULL;
    5. >   *s = 42;
    6.   }

Also looked at the results on buck and gradle

Reviewed By: cristianoc

Differential Revision: D2636991

fb-gh-sync-id: 32b9a7c