[infer] Fix `make deadcode`
Summary:
```
[*ERROR**][99281] Entering directory '/Users/scho/infer/infer/src'
[*ERROR**][99281] File "istd/IResult.mli", line 8, characters 25-43:
[*ERROR**][99281] Error: Unbound module Result.Monad_infix
[*ERROR**][99281] make[1]: *** [detect_dead_code] Error 1
make: *** [real_deadcode] Error 2
```

because of no `open! IStd`.

Reviewed By: dulmarod

Differential Revision: D19948195

fbshipit-source-id: 4f36bcb47