[infer][java] stop swallowing errors coming from compilation failures
Summary:
No longer swallow compilation failures for javac. Before this diff, the compilation failures where raised:

  > infer -- javac Test.java
  Test.java:5: error: ';' expected
    static String str = "Hello"
                               ^
  1 error

but the exit code was incorrect:

  > echo $?
  0

With this diff, the failing command is printed in standard error:

  > infer -- javac Test.java
  Javac compilation error with:

  ['javac', '-g', 'Test.java', '-J-Duser.language=en']

and the exit code is different from 0.

  > echo $?
  1